export const dashboardHtml = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Trae 模型负载</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='15' fill='%23252a31'/%3E%3Cpath d='M16 38 25 23l10 18 7-12 6 9' fill='none' stroke='white' stroke-width='5' stroke-linecap='round' stroke-linejoin='round'/%3E%3Ccircle cx='49' cy='16' r='8' fill='%2361d0ab' stroke='%23d8f5eb' stroke-width='3'/%3E%3C/svg%3E">
<style>
:root{color-scheme:light;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--page:#f5f7fa;--panel:#fff;--surface:#fff;--surface-muted:#fafbfc;--text:#30343b;--muted:#8a919a;--border:#dde1e6;--soft-border:#e5e8eb;--divider:#eef0f2;--hover:#f5f7f8;--button:#eef1f4;--button-text:#535a63;--shadow:#18223020;--icon-bg:transparent}
:root[data-theme="dark"]{color-scheme:dark;--page:#111317;--panel:#191c21;--surface:#1d2127;--surface-muted:#171a1f;--text:#e8eaed;--muted:#9299a3;--border:#30353d;--soft-border:#343a43;--divider:#2a3038;--hover:#252a31;--button:#2a3038;--button-text:#d7dbe0;--shadow:#00000066;--icon-bg:#fff}
*{box-sizing:border-box}html,body{width:100%;height:100%;overflow:hidden}body{margin:0;background:var(--page);color:var(--text);transition:background .2s,color .2s}.panel{position:fixed;inset:2.5dvh 2.5dvw;display:flex;flex-direction:column;overflow:hidden;background:var(--panel);border:1px solid var(--border);border-radius:12px;box-shadow:0 3px 14px var(--shadow),0 1px 2px var(--shadow)}.content{min-height:0;flex:1;padding:24px 20px 20px;overflow-y:auto;scrollbar-color:var(--border) transparent;scrollbar-width:thin}.section-title{margin:0 0 16px;color:var(--muted);font-size:18px;font-weight:700}.list{columns:2;column-gap:12px}.model-card{width:100%;min-width:0;margin:0 0 12px;overflow:hidden;break-inside:avoid;border:1px solid var(--soft-border);border-radius:10px;background:var(--surface)}.card-title{padding:9px 12px 7px;color:var(--muted);font-size:13px;font-weight:700;border-bottom:1px solid var(--divider);background:var(--surface-muted)}.card-models{padding:3px 4px}.model{min-height:44px;display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:10px;padding:4px 8px;border-radius:7px}.model:hover{background:var(--hover)}.logo{width:28px;height:28px;display:grid;place-items:center;position:relative}.logo img{width:27px;height:27px;object-fit:contain;background:var(--icon-bg);border-radius:6px}.available{position:absolute;right:-1px;bottom:-1px;width:9px;height:9px;border:2px solid var(--surface);border-radius:50%;background:#18bd86}.meta{min-width:0;display:flex;align-items:baseline;gap:8px;white-space:nowrap}.name{overflow:hidden;text-overflow:ellipsis;font-size:18px;font-weight:620}.tag{color:var(--muted);font-size:15px}.max{color:#08b679;background:#e8f8f2;border-radius:4px;padding:1px 5px}:root[data-theme="dark"] .max{color:#65d6af;background:#17392f}.load{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:18px;font-variant-numeric:tabular-nums}.dot{width:14px;height:14px;border:3px solid #d5f1e8;border-radius:50%;background:#67d2af}.dot.medium{border-color:#f8edc9;background:#ddb444}.dot.high{border-color:#f9dcdc;background:#eb8d8d}.empty{padding:48px 12px;text-align:center;color:var(--muted)}.footer{flex:0 0 auto;display:flex;align-items:center;gap:8px;padding:10px 22px 14px;color:var(--muted);font-size:13px;border-top:1px solid var(--divider)}.stale{color:#c59020}.action{border:0;padding:7px 10px;border-radius:7px;background:var(--button);color:var(--button-text);cursor:pointer}.theme{margin-left:auto}.action:hover{filter:brightness(.97)}
@media(prefers-color-scheme:dark){:root:not([data-theme]){color-scheme:dark;--page:#111317;--panel:#191c21;--surface:#1d2127;--surface-muted:#171a1f;--text:#e8eaed;--muted:#9299a3;--border:#30353d;--soft-border:#343a43;--divider:#2a3038;--hover:#252a31;--button:#2a3038;--button-text:#d7dbe0;--shadow:#00000066;--icon-bg:#fff}:root:not([data-theme]) .max{color:#65d6af;background:#17392f}}
@media(max-width:760px){.content{padding-inline:12px}.list{columns:1}.tag{font-size:13px}}
</style>
</head>
<body>
<main class="panel"><section class="content"><h1 class="section-title">内置模型</h1><div class="list" id="models"><div class="empty">正在读取模型数据…</div></div></section><footer class="footer"><span id="status">正在刷新…</span><button class="action theme" id="theme" type="button" aria-label="切换颜色主题">暗色</button><button class="action" id="refresh" type="button">刷新</button></footer></main>
<script>
const list=document.querySelector('#models'),status=document.querySelector('#status'),refresh=document.querySelector('#refresh'),theme=document.querySelector('#theme'),themeKey='traex-dashboard-theme';
const savedTheme=localStorage.getItem(themeKey);if(savedTheme==='light'||savedTheme==='dark')document.documentElement.dataset.theme=savedTheme;
const isDark=()=>document.documentElement.dataset.theme?document.documentElement.dataset.theme==='dark':matchMedia('(prefers-color-scheme: dark)').matches;
const updateTheme=()=>{theme.textContent=isDark()?'亮色':'暗色';theme.setAttribute('aria-label',isDark()?'切换到亮色模式':'切换到暗色模式')};
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const loadClass=load=>load>=90?'high':load>=70?'medium':'';
const getSeries=model=>{const name=(model.id+' '+model.name).toLowerCase();if(name.includes('seed')||name.includes('doubao'))return'Seed';if(name.includes('openrouter'))return'OpenRouter';if(name.includes('gpt'))return'GPT';if(name.includes('deepseek'))return'DeepSeek';if(name.includes('gemini'))return'Gemini';return'其他'};
const renderModel=model=>{const icon=model.icon?'<img src="'+escapeHtml(model.icon)+'" alt="">':'',max=model.max?'<span class="tag max">Max</span>':'',usage=model.quotaPercent===null?'':' · 周已用'+model.quotaPercent+'%',limited=model.limited?'<span class="tag">限额'+usage+'</span>':'',load=model.load===null?'<span class="tag">暂无负载</span>':'<span class="load">'+Math.round(model.load)+'%<i class="dot '+loadClass(model.load)+'"></i></span>';return'<article class="model"><div class="logo">'+icon+(model.selectable?'<i class="available"></i>':'')+'</div><div class="meta"><span class="name" title="'+escapeHtml(model.name)+'">'+escapeHtml(model.name)+'</span>'+max+limited+'</div>'+load+'</article>'};
const render=models=>{if(!models.length){list.innerHTML='<div class="empty">当前没有可用模型</div>';return}const groups=new Map;models.forEach(model=>{const series=getSeries(model);if(!groups.has(series))groups.set(series,[]);groups.get(series).push(model)});list.innerHTML=[...groups].map(([series,items])=>'<section class="model-card"><div class="card-title">'+series+'</div><div class="card-models">'+items.map(renderModel).join('')+'</div></section>').join('')};
const load=async()=>{refresh.disabled=true;status.textContent='正在刷新…';try{const response=await fetch('/v1/model-status',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error?.message||'读取失败');render(data.models);status.classList.toggle('stale',data.stale);status.textContent=(data.stale?'数据已过期 · ':'')+'数据更新时间：'+new Date(data.updatedAt).toLocaleTimeString('zh-CN')}catch(error){list.innerHTML='<div class="empty">'+escapeHtml(error.message)+'</div>';status.textContent=error.message}finally{refresh.disabled=false}};
theme.addEventListener('click',()=>{const next=isDark()?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem(themeKey,next);updateTheme()});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(!document.documentElement.dataset.theme)updateTheme()});refresh.addEventListener('click',load);updateTheme();load();setInterval(load,30000);
</script>
</body>
</html>`;
